---
- name: This is a hello-world example
  hosts: 192.168.210.102

  tasks:
    - name: Create a file called '/tmp/testfile.txt' with the content 'hello world'.
      copy:
        content: hello worldn
        dest: /tmp/{{ dynamic_value }}