---
- name: This is runnin a scrpit example
  hosts: 192.168.210.102

  tasks:
    - name: Execue script cycle 1
      command: sh /tmp/script.sh archivo1.txt

    - name: Execue script cycle 2
      command: sh /tmp/script.sh archivo2.txt

    - name: Execue script cycle 3
      command: sh /tmp/script.sh archivo3.txt
