---
- name: Set new hostname and IP
  hosts: 192.168.29.109
  become: yes
  
  tasks:
      
    - name: "update hostnames"
      hostname:
        name: "{{ new-hostname }}"
    
    #- name: Set hostname
    #  ansible.builtin.hostname:
    #    name: "{{ new-hostname }}"
        
    #- name: Set new IP adress
    #  ip: "{{host-new-ip}}"
    #  interface: eth0