---
- name: Set new hostname and IP
  hosts: {{host-current-ip}}
  become: yes
  
  tasks:

    - name: Set hostname 
      ansible.builtin.hostname:
        name: "{{new-hotname}}"
        
    #- name: Set new IP adress
    #  ip: "{{host-new-ip}}"
    #  interface: eth0